### ISSUE TITLE
Post INSIGHT LDD JSON and ZIP for v1600

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/portal-tasks#40]
## 💡 Description

Per https://github.com/NASA-PDS/registry/issues/84:
- [ ] put JSON online here: https://pds.nasa.gov/pds4/mission/insight/v1/
- [ ] update https://pds.nasa.gov/datastandards/dictionaries/index-missions.shtml#insight with the new links.
- [ ] close https://github.com/NASA-PDS/registry/issues/84
- [ ] notify Irma from ATM that this is fixed

**Comment by c-suh** [comment]
@jordanpadams the existing PDS4_INSIGHT_1600 files (xsd, sch, xml) are for IM v1.8.0.0, whereas the ones you created are for IM v1.11.0.0 aka v1B00. Since the filenames are the same, they cannot both be present. Confirming that I should delete the subsection for "**Version:** 1.8.0.0" under https://pds.nasa.gov/datastandards/dictionaries/index-missions.shtml#insight and create an additional subsection for "**Version:** 1.11.0.0" to the bottom of the existing v1.11.0.0s?

**Comment by jordanpadams** [comment]
@c-suh post just this JSON instead (manually changed the IM version):

[PDS4_INSIGHT_1600.JSON.zip](https://github.com/NASA-PDS/portal-tasks/files/9366436/PDS4_INSIGHT_1600.JSON.zip)
